export const DEFAULT_PRODUCTS = [
  {
    slug: 'articulated-dragon',
    name: 'Articulated Dragon',
    description: 'A fully flexible printed dragon with stunning details.',
    fullDescription:
      'This articulated dragon is designed with precision joints that allow for smooth, realistic movement. Perfect for collectors and enthusiasts of fantasy art, this 3D printed marvel combines intricate detailing with functional flexibility.',
    material: 'PLA',
    price: 1599,
    image: '/products/dragon.png',
    imageColor: 'from-[#ff7e5f] to-[#feb47b]',
    type: 'Collectibles',
    dimensions: '25cm x 15cm x 10cm',
    weight: '150g',
    printTime: '8-10 hours',
    inStock: true,
  },
  {
    slug: 'minimalist-headphone-stand',
    name: 'Minimalist Headphone Stand',
    description: 'Sleek geometric design to keep your desk organized.',
    fullDescription:
      'A minimalist headphone stand with clean geometric lines. Designed to complement modern desk setups while providing sturdy support for your headphones. Perfect for productivity enthusiasts.',
    material: 'PETG',
    price: 999,
    image: '/products/headphone-stand.png',
    imageColor: 'from-[#2193b0] to-[#6dd5ed]',
    type: 'Desk Accessories',
    dimensions: '20cm x 8cm x 12cm',
    weight: '80g',
    printTime: '4-5 hours',
    inStock: true,
  },
  {
    slug: 'topology-planter',
    name: 'Topology Planter',
    description: 'Mathematical topological surface designed for indoor plants.',
    fullDescription:
      'A mathematically inspired planter with a unique topological surface pattern. The organic, flowing design creates visual interest while providing a functional home for small indoor plants.',
    material: 'PLA',
    price: 2499,
    image: '/products/planter.png',
    imageColor: 'from-[#11998e] to-[#38ef7d]',
    type: 'Home Decor',
    dimensions: '15cm height',
    weight: '120g',
    printTime: '6-7 hours',
    inStock: true,
  },
  {
    slug: 'ergonomic-macropad-case',
    name: 'Ergonomic Macropad Case',
    description: 'Custom 3D printed case for 9-key mechanical macropads.',
    fullDescription:
      'A fully customizable ergonomic case for your 9-key mechanical macropad. Features a contoured design for comfortable palm rest and precision cutouts for all components.',
    material: 'ABS',
    price: 850,
    image: '',
    imageColor: 'from-[#bdc3c7] to-[#2c3e50]',
    type: 'Kit Cards',
    dimensions: '12cm x 10cm x 5cm',
    weight: '95g',
    printTime: '5-6 hours',
    inStock: true,
  },
  {
    slug: 'voronoi-pen-holder',
    name: 'Voronoi Pen Holder',
    description: 'Abstract voronoi patterned desk accessory.',
    fullDescription:
      'An artistic desk accessory featuring a beautiful Voronoi pattern. The abstract geometric design creates a stunning visual centerpiece while keeping pens and markers organized.',
    material: 'TPU',
    price: 1200,
    image: '',
    imageColor: 'from-[#8e2de2] to-[#4a00e0]',
    type: 'Home Decor',
    dimensions: '10cm x 10cm x 8cm',
    weight: '110g',
    printTime: '5.5 hours',
    inStock: true,
  },
  {
    slug: 'mechanical-gyroscope',
    name: 'Mechanical Gyroscope',
    description: 'Print-in-place moving mechanical toy.',
    fullDescription:
      'A fully functional mechanical gyroscope that prints as one assembled piece. Watch it spin with satisfying precision engineering. A perfect desk toy and conversation starter.',
    material: 'PLA',
    price: 550,
    image: '',
    imageColor: 'from-[#f12711] to-[#f5af19]',
    type: 'Playables',
    dimensions: '8cm diameter',
    weight: '70g',
    printTime: '3-4 hours',
    inStock: true,
  },
];
